
master_dict = {'absurd': 'a situation in which life seems irrational and meaningless',
               'abyss': 'a bottomless gulf or pit; any unfathomable (or apparently unfathomable',
               'affix': 'a linguistic element added to a word to produce an inflected or derived form',
               'avenue': 'a line of approach',
               'axiom': 'a saying that is widely accepted on its own merits',
               'azure': 'a light shade of blue',
               'bagpipes': 'a tubular wind instrument; the player blows air into a bag and squeezes it out through the drone',
               'bandwagon': 'a popular trend that attracts growing support',
               'banjo': 'a stringed instrument of the guitar family that has long neck and circular body',
               'bayou': 'a swampy arm or slow-moving outlet of a lake (term used mainly in Mississippi and Louisiana',
               'beekeeper': 'a farmer who keeps bees for their honey',
               'bikini': 'an atoll in the Marshall Islands; formerly used by the United States as a site for testing nuclear weapons',
               'blitz': 'a swift and violent military offensive with intensive aerial bombardment',
               'blizzard': 'a storm with widespread snowfall accompanied by strong winds',
               'bookworm': 'a person who pays more attention to formal rules and book learning than they merit',
               'boxcar': 'a freight car with roof and sliding doors in the sides',
               'boxful': 'the quantity contained in a box',
               'buckaroo': "local names for a cowboy (`vaquero' is used especially in southwestern and central Texas and `buckaroo' is used especially in California",
               'buffalo': 'large shaggy-haired brown bison of North American plains',
               'buffoon': 'a rude or vulgar fool',
               'buzzard': 'a New World vulture that is common in South America and Central America and the southern United States',
               'buzzwords': 'stock phrases that have become nonsense through endless repetition',
               'caliph': 'the civil and religious leader of a Muslim state considered to be a representative of Allah on earth',
               'cobweb': 'a fabric so delicate and transparent as to resemble a web of a spider',
               'cockiness': 'offensive boldness and assertiveness',
               'croquet': 'a game in which players hit a wooden ball through a series of hoops; the winner is the first to traverse all the hoops and hit a peg',
               'crypt': 'a cellar or vault or underground burial chamber (especially beneath a church',
               'curacao': 'a popular island resort in the Netherlands Antilles',
               'cycle': 'an interval during which a recurring sequence of events occurs',
               'daiquiri': 'a cocktail made with rum and lime or lemon juice',
               'dirndl': 'a full skirt with a gathered waistband',
               'duplex': 'a house with two units sharing a common wall',
               'dwarves': 'a person who is markedly small',
               'espionage': 'the systematic use of spies to get military or political secrets',
               'exodus': 'a journey by a large group to escape from a hostile environment',
               'fishhook': 'a sharp barbed hook for catching fish',
               'fjord': 'a long narrow inlet of the sea between steep cliffs; common in Norway',
               'flapjack': 'a flat cake of thin batter fried on both sides on a griddle',
               'fluffiness': 'a light softness',
               'foxglove': 'any of several plants of the genus Digitalis',
               'fuchsia': 'any of various tropical shrubs widely cultivated for their showy drooping purplish or reddish or white flowers; Central and South America and New Zealand and Tahiti',
               'funny': 'an account of an amusing incident (usually with a punch line',
               'galaxy': 'a splendid assemblage (especially of famous people',
               'gazebo': 'a small roofed building affording shade and rest',
               'gizmo': 'something unspecified whose name is either forgotten or not known',
               'glowworm': 'the luminous larva or wingless grub-like female of a firefly',
               'glyph': 'glyptic art in the form of a symbolic figure carved or incised in relief',
               'gnostic': 'an advocate of Gnosticism',
               'gossip': 'light informal conversation for social occasions',
               'grogginess': 'a dazed and staggering state caused by alcohol',
               'haiku': 'an epigrammatic Japanese verse form of three short lines',
               'hyphen': 'a punctuation mark',
               'icebox': 'white goods in which food can be stored at low temperatures',
               'injury': 'any physical damage to the body caused by violence or accident or fracture etc.',
               'ivory': 'a hard smooth ivory colored dentine that makes up most of the tusks of elephants and walruses',
               'ivy': 'Old World vine with lobed evergreen leaves and black berrylike fruits',
               'jackpot': 'the cumulative amount involved in a game (such as poker',
               'jaundice': 'yellowing of the skin and the whites of the eyes caused by an accumulation of bile pigment (bilirubin',
               'jawbreaker': 'a large round hard candy',
               'jelly': 'a preserve made of the jelled juice of fruit',
               'jigsaw': 'a portable power saw with a reciprocating blade; can be used with a variety of blades depending on the application and kind of cut; generally have a plate that rides on the surface that is being cut',
               'jinx': 'a person believed to bring bad luck to those around him',
               'jiujitsu': "a method of self-defense without weapons that was developed in China and Japan; holds and blows are supplemented by clever use of the attacker's own weight and strength",
               'jockey': 'someone employed to ride horses in horse races',
               'jogging': 'running at a jog trot as a form of cardiopulmonary exercise',
               'jukebox': 'a cabinet containing an automatic record player; records are played by inserting a coin',
               'kayak': 'a small canoe consisting of a light frame made watertight with animal skins; used by Eskimos',
               'kazoo': 'a toy wind instrument that has a membrane that makes a sound when you hum into the mouthpiece',
               'keyhole': 'the hole where a key is inserted',
               'khaki': 'a sturdy twilled cloth of a yellowish brown color used especially for military uniforms',
               'kilobyte': 'a unit of information equal to 1000 bytes',
               'kiosk': 'small area set off by walls for special use',
               'kitsch': 'excessively garish or sentimental art; usually considered in bad taste',
               'klutz': '(Yiddish',
               'knapsack': 'a bag carried by a strap on your back or shoulder',
               'larynx': 'a cartilaginous structure at the top of the trachea; contains elastic vocal cords that are the source of the vocal tone in speech',
               'lengths': 'the linear extent in space from one end to the other; the longest dimension of something that is fixed in place',
               'luxury': 'something that is an indulgence rather than a necessity',
               'lymph': 'a thin coagulable fluid (similar to plasma but',
               'marquis': 'humorist who wrote about the imaginary life of cockroaches (1878-1937',
               'matrix': '(mathematics',
               'megahertz': 'one million periods per second',
               'microwave': 'a short electromagnetic wave (longer than infrared but shorter than radio waves',
               'mnemonic': 'a device (such as a rhyme or acronym',
               'naphtha': 'any of various volatile flammable liquid hydrocarbon mixtures; used chiefly as solvents',
               'nightclub': 'a spot that is open late at night and that provides entertainment (as singers or dancers',
               'nowadays': 'the period of time that is happening now; any continuous stretch of time including the moment of speech',
               'nymph': '(classical mythology',
               'onyx': 'a chalcedony with alternating black and white bands; used in making cameos',
               'ovary': 'the organ that bears the ovules of a flower',
               'oxygen': "a nonmetallic bivalent element that is normally a colorless odorless tasteless nonflammable diatomic gas; constitutes 21 percent of the atmosphere by volume; the most abundant element in the earth's crust",
               'pajama': 'a pair of loose trousers tied by a drawstring around the waist; worn by men and women in some Asian countries',
               'peekaboo': 'a game played with young children; you hide your face and suddenly reveal it as you say boo!',
               'phlegm': 'apathy demonstrated by an absence of emotional reactions',
               'pixel': 'usually a colored dot',
               'pneumonia': 'respiratory disease characterized by inflammation of the lung parenchyma (excluding the bronchi',
               'polka': 'music performed for dancing the polka',
               'psyche': "that which is responsible for one's thoughts, feelings, and conscious brain functions; the seat of the faculty of reason",
               'puppy': 'a young dog',
               'quartz': 'colorless glass made of almost pure silica',
               'queue': 'a line of people or vehicles waiting for something',
               'quips': 'a witty saying',
               'quiz': 'an examination consisting of a few short questions',
               'quizzes': 'an examination consisting of a few short questions',
               'quorum': 'a gathering of the minimal number of members of an organization to conduct business',
               'razzmatazz': 'any exciting and complex play intended to confuse (dazzle',
               'rhubarb': 'long pinkish sour leafstalks usually eaten cooked and sweetened',
               'rhythm': 'the basic rhythmic unit in a piece of music',
               'rickshaw': 'a small two-wheeled cart for one passenger; pulled by one person',
               'schnapps': 'any of various strong liquors especially a Dutch spirit distilled from potatoes',
               'scratch': 'an abraded area where the skin is torn or worn off',
               'shiv': 'a knife used as a weapon',
               'sphinx': 'an inscrutable person who keeps his thoughts and intentions secret',
               'spritz': 'a quick squirt of some liquid (usually carbonated water',
               'squawk': 'the noise of squawking',
               'staff': 'personnel who assist their superior in carrying out an assigned task',
               'strength': 'the property of being physically or mentally strong',
               'strengths': 'the property of being physically or mentally strong',
               'stretch': 'a large and unbroken expanse or distance',
               'stronghold': 'a strongly fortified defensive structure',
               'subway': 'an electric railway operating below the surface of the ground (usually in a city',
               'swivel': 'a coupling (as in a chain',
               'syndrome': 'a complex of concurrent things',
               'thumbscrew': 'instrument of torture that crushes the thumb',
               'topaz': 'a yellow quartz',
               'transcript': 'something that has been transcribed; a written record (usually typewritten',
               'transplant': 'the act of removing something from one location and introducing it in another location',
               'twelfth': 'position 12 in a countable series of things',
               'twelfths': 'position 12 in a countable series of things',
               'unknown': 'an unknown and unexplored region',
               'uptown': 'a residential part of town away from the central commercial district',
               'vixen': 'a malicious woman with a fierce temper',
               'vodka': 'unaged colorless liquor originating in Russia',
               'voodoo': 'a charm superstitiously believed to embody magical powers',
               'vortex': 'the shape of something rotating rapidly',
               'voyeurism': "a perversion in which a person receives sexual gratification from seeing the genitalia of others or witnessing others' sexual behavior",
               'walkway': 'a path set aside for walking',
               'waltz': 'an assured victory (especially in an election',
               'wave': 'one of a series of ridges that moves across the surface of a liquid (especially across a large body of water',
               'wellspring': 'the source of water for a well',
               'whiskey': 'a liquor made from fermented mash of grain',
               'witchcraft': 'the art of sorcery',
               'wizard': 'someone who is dazzlingly skilled in any field',
               'wristwatch': 'a watch that is worn strapped to the wrist',
               'wyvern': 'a fire-breathing dragon used in medieval heraldry; had the head of a dragon and the tail of a snake and a body with wings and two legs',
               'xylophone': 'a percussion instrument with wooden bars tuned to produce a chromatic scale and with resonators; played with small mallets',
               'yachtsman': 'a person who owns or sails a yacht',
               'zephyr': 'a slight wind (usually refreshing',
               'zigzag': 'an angular shape characterized by sharp turns in alternating directions',
               'zilch': 'a quantity of no importance',
               'zipper': 'a fastener for locking together two toothed edges by means of a sliding tab',
               'zodiac': 'a belt-shaped region in the heavens on either side to the ecliptic; divided into 12 constellations or signs for astrological purposes',
               'apple': 'fruit with red or yellow or green skin and sweet to tart crisp whitish flesh',
               'ball': 'round object that is hit or thrown or kicked in games',
               'banana': 'any of several tropical and subtropical treelike herbs of the genus Musa having a terminal crown of large entire leaves and usually bearing hanging clusters of elongated fruits',
               'beach': 'an area of sand sloping down to the water of a sea or lake',
               'bed': 'a piece of furniture that provides a place to sleep',
               'bird': 'warm-blooded egg-laying vertebrates characterized by feathers and forelimbs modified as wings',
               'book': 'a written work or composition that has been published (printed on pages bound together',
               'boy': 'a youthful male person',
               'bug': 'general term for any insect or similar creeping or crawling invertebrate',
               'cat': 'feline mammal usually having thick soft fur and no ability to roar: domestic cats; wildcats',
               'cheese': 'a solid food prepared from the pressed curd of milk',
               'circle': 'ellipse in which the two axes are of equal length; a plane curve generated by one point moving at a constant distance from a fixed point',
               'coat': 'an outer garment that has sleeves and covers the body from shoulder down; worn outdoors',
               'cone': 'any cone-shaped artifact',
               'cookie': "any of various small flat sweet cakes (`biscuit' is the British term",
               'cow': "mature female of mammals of which the male is called `bull'",
               'cream': 'the best people or things in a group',
               'cup': 'a small open container usually used for drinking; usually has a handle',
               'dog': 'a member of the genus Canis (probably descended from the common wolf',
               'drum': 'a musical percussion instrument; usually consists of a hollow cylinder with a membrane stretched across each end',
               'duck': 'small wild or domesticated web-footed broad-billed swimming bird usually having a depressed body and short legs',
               'egg': 'animal reproductive body consisting of an ovum or embryo together with nutritive and protective envelopes; especially the thin-shelled reproductive body laid by e.g. female birds',
               'eyes': 'the organ of sight',
               'face': 'the front of the human head from the forehead to the chin and ear to ear',
               'flower': 'a plant cultivated for its blooms or blossoms',
               'ghost': 'a mental representation of some haunting experience',
               'girl': 'a young female',
               'hat': 'headdress that protects the head from bad weather; has shaped crown and usually a brim',
               'heart': 'the locus of feelings and intuitions',
               'hippo': 'an ancient Numidian town in northwestern Africa adjoining present-day Annaba in northeastern Algeria',
               'house': 'a dwelling that serves as living quarters for one or more families',
               'ice': 'water frozen in the solid state',
               'jacket': 'a short coat',
               'jar': 'a vessel (usually cylindrical',
               'kite': 'a bank check that has been fraudulently altered to increase its face value',
               'light': 'any device serving as a source of illumination',
               'lips': 'either of two fleshy folds of tissue that surround the mouth and play a role in speaking',
               'milk': 'a white nutritious liquid secreted by mammals and used as food by human beings',
               'mouse': 'any of numerous small rodents typically resembling diminutive rats having pointed snouts and small ears on elongated bodies with slender usually hairless tails',
               'mouth': 'the opening through which food is taken in and vocalizations emerge',
               'nose': 'the organ of smell and entrance to the respiratory tract; the prominent part of the face of man or other mammals',
               'ocean': 'a large body of water constituting a principal part of the hydrosphere',
               'person': 'a human being',
               'pie': 'dish baked in pastry-lined pan often with a pastry top',
               'shirt': 'a garment worn on the upper half of the body',
               'shoe': 'footwear shaped to fit the foot (below the ankle',
               'skateboard': 'a board with wheels that is ridden in a standing or crouching position and propelled by foot',
               'slide': 'a small flat rectangular piece of glass on which specimens can be mounted for microscopic study',
               'smile': 'a facial expression characterized by turning up the corners of the mouth; usually shows pleasure or amusement',
               'snake': 'limbless scaly elongate reptile; some are venomous',
               'snowflake': 'a crystal of snow',
               'socks': 'hosiery consisting of a cloth covering for the foot; worn inside the shoe; reaches to between the ankle and the knee',
               'spider': 'predatory arachnid with eight legs, two poison fangs, two feelers, and usually two silk-spinning organs at the back end of the body; they spin silk to make cocoons for eggs or traps for prey',
               'spoon': 'a piece of cutlery with a shallow bowl-shaped container and a handle; used to stir or serve or take up food',
               'star': 'any celestial body visible as a point of light',
               'sun': 'the star that is the source of light and heat for the planets in the solar system',
               'swing': 'a state of steady vigorous action that is characteristic of an activity',
               'tree': 'a tall perennial woody plant having a main trunk and branches forming a distinct elevated crown; includes both gymnosperms and angiosperms',
               'water': 'binary compound that occurs at room temperature as a clear colorless odorless tasteless liquid; freezes into ice below 0 degrees centigrade and boils above 100 degrees centigrade; widely used as a solvent',
               'web': 'an intricate network suggesting something that was formed by weaving or interweaving',
               'whale': 'a very large person; impressive in size or qualities',
               'worm': 'any of numerous relatively small elongated soft-bodied animals especially of the phyla Annelida and Chaetognatha and Nematoda and Nemertea and Platyhelminthes; also many insect larvae'}

easy_list = ['apple', 'ball', 'banana', 'beach', 'bed', 'bird', 'book', 'boy', 'bug', 'cat', 'cheese', 'circle', 'coat', 'cone', 'cookie', 'cow', 'cream', 'cup', 'dog', 'drum', 'duck', 'egg', 'eyes', 'face', 'flower', 'ghost', 'girl', 'hat', 'heart', 'hippo', 'house',
             'ice', 'jacket', 'jar', 'kite', 'light', 'lips', 'milk', 'mouse', 'mouth', 'nose', 'ocean', 'person', 'pie', 'shirt', 'shoe', 'skateboard', 'slide', 'smile', 'snake', 'snowflake', 'socks', 'spider', 'spoon', 'star', 'sun', 'swing', 'tree', 'water', 'web', 'whale', 'worm']
hard_list = ['absurd', 'abyss', 'affix', 'avenue', 'axiom', 'azure', 'bagpipes', 'bandwagon', 'banjo', 'bayou', 'beekeeper', 'bikini', 'blitz', 'blizzard', 'bookworm', 'boxcar', 'boxful', 'buckaroo', 'buffalo', 'buffoon', 'buzzard', 'buzzwords', 'caliph', 'cobweb', 'cockiness', 'croquet', 'crypt', 'curacao', 'cycle', 'daiquiri', 'dirndl', 'duplex', 'dwarves', 'espionage', 'exodus', 'fishhook', 'fjord', 'flapjack', 'fluffiness', 'foxglove', 'fuchsia', 'funny', 'galaxy', 'gazebo', 'gizmo', 'glowworm', 'glyph', 'gnostic', 'gossip', 'grogginess', 'haiku', 'hyphen', 'icebox', 'injury', 'ivory', 'ivy', 'jackpot', 'jaundice', 'jawbreaker', 'jelly', 'jigsaw', 'jinx', 'jiujitsu', 'jockey', 'jogging', 'jukebox', 'kayak', 'kazoo', 'keyhole', 'khaki', 'kilobyte', 'kiosk', 'kitsch', 'klutz', 'knapsack', 'larynx',
             'lengths', 'luxury', 'lymph', 'marquis', 'matrix', 'megahertz', 'microwave', 'mnemonic', 'naphtha', 'nightclub', 'nowadays', 'nymph', 'onyx', 'ovary', 'oxygen', 'pajama', 'peekaboo', 'phlegm', 'pixel', 'pneumonia', 'polka', 'psyche', 'puppy', 'quartz', 'queue', 'quips', 'quiz', 'quizzes', 'quorum', 'razzmatazz', 'rhubarb', 'rhythm', 'rickshaw', 'schnapps', 'scratch', 'shiv', 'sphinx', 'spritz', 'squawk', 'staff', 'strength', 'strengths', 'stretch', 'stronghold', 'subway', 'swivel', 'syndrome', 'thumbscrew', 'topaz', 'transcript', 'transplant', 'twelfth', 'twelfths', 'unknown', 'uptown', 'vixen', 'vodka', 'voodoo', 'vortex', 'voyeurism', 'walkway', 'waltz', 'wave', 'wellspring', 'whiskey', 'witchcraft', 'wizard', 'wristwatch', 'wyvern', 'xylophone', 'yachtsman', 'zephyr', 'zigzag', 'zilch', 'zipper', 'zodiac']
